services:
  # mysql Database
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
    networks:
      - wpnetwork

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpnetwork

  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 8085:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: secret
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes: ["./:/var/www/html"]
    networks:
      - wpnetwork

networks:
  wpnetwork:
volumes:
  db_data: